# Read the Docs configuration file
# https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

# Tell RTD how to build the Sphinx docs
sphinx:
  configuration: docs/conf.py

python:
  install:
    # Install your package
    - method: pip
      path: .

    # Install documentation dependencies
    - requirements: docs/requirements.txt
